version: '3.8'

services:
  product-service:
    image: pamitha/product-service:latest
    ports:
      - "8081:8081"
    restart: always

  order-service:
    image: pamitha/order-service:latest
    ports:
      - "8082:8082"
    restart: always

  inventory-service:
    image: pamitha/inventory-service:latest
    ports:
      - "8083:8083"
    restart: always

  api-gateway:
    image: pamitha/api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - inventory-service
    restart: always
