version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    restart: always

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    restart: always

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8083:8083"
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - inventory-service
    restart: always
